name: Test Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-that-fails:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  test-that-fails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: npm test
      - if: failure()
        run: echo 'test-that-fails job indeed failed'
  test-that-passes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: npm test -- --pleasePass
  summary-job:
    needs: [build-that-fails, test-that-fails, test-that-passes]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "build-that-fails: ${{ needs.build-that-fails.result }}"
          echo "test-that-fails: ${{ needs.test-that-fails.result }}"
          echo "test-that-passes: ${{ needs.test-that-passes.result }}"
          failed_count=$(echo '${{ join(needs.*.result) }}' | grep -o failure | wc -l)
          echo $failed_count > failed-count.txt
      - uses: actions/upload-artifact@v7
        with:
          name: failed-count-artifact
          path: failed-count.txt
